### ISSUE TITLE
Config directory not found unless forward slashes are used

### ISSUE THREAD

**Issue by bphillips09** [mjcumming/ISY-Homie-Bridge#4]
On the latest Raspbian image, the service fails to start and throws an error here in [isy_homie_start.py](https://github.com/mjcumming/ISY-Homie-Bridge/blob/master/isy_homie_start.py):

```python
with open("\etc\isy_homie.yml", 'r') as ymlfile:
    cfg = yaml.full_load(ymlfile)
```

However, if forward-slashes are used in the file path instead, it works as intended:

```python
with open("/etc/isy_homie.yml", 'r') as ymlfile:
    cfg = yaml.full_load(ymlfile)
```

**Comment by mjcumming** [comment]
fixed!
